POST http://localhost:3000/login/
Content-Type: application/json
{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE3NTkzODkxfQ.CHT26LZmvYj8iD8GPkwAW_32-7YRH-8AikoPrUnWllI

###
GET http://localhost:3000/states/8/

###
GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE3NTkzODkxfQ.CHT26LZmvYj8iD8GPkwAW_32-7YRH-8AikoPrUnWllI

###
POST http://localhost:3000/districts/
Content-Type: application/json
{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###
POST http://localhost:3000/districts/
Content-Type: application/json
{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
Authorization Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE3NTkzODkxfQ.CHT26LZmvYj8iD8GPkwAW_32-7YRH-8AikoPrUnWllI

###
GET http://localhost:3000/districts/43/

###
GET http://localhost:3000/districts/43/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE3NTkzODkxfQ.CHT26LZmvYj8iD8GPkwAW_32-7YRH-8AikoPrUnWllI

###
DELETE http://localhost:3000/districts/765/

###
DELETE http://localhost:3000/districts/765/
Authorization Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE3NTkzODkxfQ.CHT26LZmvYj8iD8GPkwAW_32-7YRH-8AikoPrUnWllI

###
PUT http://localhost:3000/districts/43/
Content-Type: application/json
{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###
GET http://localhost:3000/states/4/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzE3NTkzODkxfQ.CHT26LZmvYj8iD8GPkwAW_32-7YRH-8AikoPrUnWllI

###
GET http://localhost:3000/states/3/stats/
